In [6]:
from lib.data import get_data
from lib.stats import stage_standing, match_standing

df = get_data("fitds_stages")

stage_df = stage_standing(df, 'monster_2025', 'P', 1)
match_df = match_standing(df, 'ma5_1_2026', 'PO')

2026-03-14 18:08:22.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [7]:
match_df

,shooter_div,rank,class_rank,shooter_name,shooter_class,stg_match_pts,pct,class_pct
0,PO,1,1,"CASTELLETTI , PAOLO",D,748.085,1.0000,1.0000
1,PO,2,1,"PIACENTINI , ANDREA",A,727.312,0.9722,1.0000
2,PO,3,1,"AMIRANDA, CRISTIAN",M,709.308,0.9482,1.0000
3,PO,4,2,"ABRAMO, FRANCESCO",A,707.545,0.9458,0.9728
4,PO,5,3,"GALEAZZI, MAURIZIO",A,675.225,0.9026,0.9284
5,PO,6,2,"DONATI, EDOARDO",M,667.417,0.8922,0.9409
6,PO,7,3,"VOLPE, ORONZO",M,651.787,0.8713,0.9189
7,PO,8,4,"MANCINI, FEDERICO",A,621.338,0.8306,0.8543
8,PO,9,5,"GALLI, MASSIMILIANO",A,621.283,0.8305,0.8542
9,PO,10,1,"PETRILLO, CARMINE",B,595.188,0.7956,1.0000
10,PO,11,2,"DI GIOVANNI, LUCA",D,578.534,0.7734,0.7734
11,PO,12,2,"DI PIETRANTONIO, LUCA",B,560.477,0.7492,0.9417
12,PO,13,3,"CAPORALI, GIORGIO",B,550.592,0.7360,0.9251
13,PO,14,4,"DARI, MASSIMILIANO",B,540.292,0.7222,0.9078
14,PO,15,5,"DELLA BINA, DAVID",B,533.442,0.7131,0.8963
15,PO,16,1,"SACCHETTI, CARLO",C,515.190,0.6887,1.0000
16,PO,17,6,"VENTURA, ANTONIO",B,514.434,0.6877,0.8643
17,PO,18,6,"PALAMARA, FRANCESCO",A,511.850,0.6842,0.7038
18,PO,19,7,"IORIO, GENNARO",B,504.768,0.6747,0.8481
19,PO,20,2,"CAPORALI, GIANLUCA",C,501.416,0.6703,0.9733
20,PO,21,3,"PATRIZI, LEANDRO",C,497.336,0.6648,0.9653
21,PO,22,4,"NOVIELLO, ROBERTO",C,487.345,0.6515,0.9460
22,PO,23,8,"FRAPPETTA, GIULIO",B,472.428,0.6315,0.7937
23,PO,24,5,"NARDUCCI, DOMENICO",C,460.613,0.6157,0.8941
24,PO,25,3,"MORZELLA, DANIELE",D,442.004,0.5908,0.5908
25,PO,26,6,"DI LORENZO, CIVITA",C,439.450,0.5874,0.8530
26,PO,27,4,"PAPALE, PIERFRANCESCO",D,421.203,0.5630,0.5630
27,PO,28,7,"SICA, LUCIO ELIO",C,395.621,0.5288,0.7679
28,PO,29,5,"GRANATO, DARIO",D,374.411,0.5005,0.5005

In [3]:
df[(df['shooter_name'] == 'ABATECOLA, CHRISTIAN') & (df['match_name'] == 'ma5_2_2025')]

,match_name,match_level,match_date,shooter_name,shooter_div,shooter_class,shooter_pf,shooter_cat,stg_n,hf,...,div_pts_perc_abcd,div_first_time_abcd,div_time_perc_abcd,div_factor_perc_abcd,div_factor_standing_abcd,cls_pts_perc_abcd,cls_first_time_abcd,cls_time_perc_abcd,cls_factor_perc_abcd,cls_factor_standing_abcd
1328,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,1,4.6523,...,0.833333,15.19,0.743879,0.673719,11.0,0.833333,17.88,0.875612,0.815521,3.0
1329,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,2,3.5685,...,0.716667,10.99,0.912033,0.700324,3.0,0.741379,12.05,1.000000,1.000000,1.0
1330,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,3,6.8875,...,1.000000,17.87,0.778989,0.854719,4.0,1.000000,21.41,0.933304,1.000000,1.0
1331,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,4,5.5264,...,0.983051,15.47,0.737018,0.777217,12.0,1.000000,19.06,0.908051,0.957582,4.0
1332,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,5,4.5313,...,0.966667,10.24,0.800000,0.828555,7.0,1.000000,12.80,1.000000,1.000000,1.0
1333,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,6,5.1048,...,0.965517,7.77,0.708295,0.735636,7.0,0.965517,9.38,0.855059,0.855061,2.0
1334,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,7,4.6656,...,1.000000,11.27,0.832815,0.906575,5.0,1.000000,12.03,0.935459,0.935459,2.0
1335,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,8,6.6667,...,1.000000,19.35,0.748333,0.848688,8.0,1.000000,23.41,0.975417,0.987762,2.0