In [1]:
from lib.data import get_data
from lib.stats import stage_standing, match_standing

df = get_data("fitds_stages")

stage_df = stage_standing(df, 'monster_2025', 'P', 1)
match_df = match_standing(df, 'ma5_1_2026', 'PO')

2026-03-15 22:29:09.338 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-15 22:29:09.339 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-15 22:29:09.340 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-15 22:29:09.342 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-15 22:29:09.342 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-03-15 22:29:09.345 No runtime found, using MemoryCacheStorageManager

In [2]:
df[df['match_name'] == 'christmas_2025']

,match_name,match_level,match_date,shooter_name,shooter_div,shooter_class,shooter_pf,shooter_cat,stg_n,hf,...,div_pts_perc_abcd,div_first_time_abcd,div_time_perc_abcd,div_factor_perc_abcd,div_factor_standing_abcd,cls_pts_perc_abcd,cls_first_time_abcd,cls_time_perc_abcd,cls_factor_perc_abcd,cls_factor_standing_abcd
27548,christmas_2025,3,2025-12-14,"SANTARCANGELO, ADRIANO CIRO",S,G,Major,SS,1,7.1152,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27549,christmas_2025,3,2025-12-14,"SANTARCANGELO, ADRIANO CIRO",S,G,Major,SS,2,5.8824,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27550,christmas_2025,3,2025-12-14,"SANTARCANGELO, ADRIANO CIRO",S,G,Major,SS,3,5.3521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27551,christmas_2025,3,2025-12-14,"SANTARCANGELO, ADRIANO CIRO",S,G,Major,SS,4,7.3511,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27552,christmas_2025,3,2025-12-14,"SANTARCANGELO, ADRIANO CIRO",S,G,Major,SS,5,7.3155,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30603,christmas_2025,3,2025-12-14,"RUSSO, MASSIMILIANO",P,A,Minor,NaN,8,4.3059,...,0.966667,11.50,0.789161,0.884241,14.0,0.966667,11.50,0.853749,0.905000,4.0
30604,christmas_2025,3,2025-12-14,"RUSSO, MASSIMILIANO",P,A,Minor,NaN,9,3.6166,...,1.000000,12.19,0.681133,0.791292,21.0,1.000000,13.34,0.804099,0.831823,5.0
30605,christmas_2025,3,2025-12-14,"RUSSO, MASSIMILIANO",P,A,Minor,NaN,10,6.1442,...,0.975000,22.47,0.838125,0.908287,5.0,1.000000,22.56,0.888539,0.924093,4.0
30606,christmas_2025,3,2025-12-14,"RUSSO, MASSIMILIANO",P,A,Minor,NaN,11,6.0134,...,0.931034,8.36,0.930958,1.000000,1.0,0.964286,8.98,1.000000,1.000000,1.0
30607,christmas_2025,3,2025-12-14,"RUSSO, MASSIMILIANO",P,A,Minor,NaN,12,6.8060,...,0.950000,16.68,0.995821,1.000000,1.0,0.982759,16.75,1.000000,1.000000,1.0

In [3]:
df[(df['shooter_name'] == 'ABATECOLA, CHRISTIAN') & (df['match_name'] == 'ma5_2_2025')]

,match_name,match_level,match_date,shooter_name,shooter_div,shooter_class,shooter_pf,shooter_cat,stg_n,hf,...,div_pts_perc_abcd,div_first_time_abcd,div_time_perc_abcd,div_factor_perc_abcd,div_factor_standing_abcd,cls_pts_perc_abcd,cls_first_time_abcd,cls_time_perc_abcd,cls_factor_perc_abcd,cls_factor_standing_abcd
1328,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,1,4.6523,...,0.833333,15.19,0.743879,0.673719,11.0,0.833333,17.88,0.875612,0.815521,3.0
1329,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,2,3.5685,...,0.716667,10.99,0.912033,0.700324,3.0,0.741379,12.05,1.000000,1.000000,1.0
1330,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,3,6.8875,...,1.000000,17.87,0.778989,0.854719,4.0,1.000000,21.41,0.933304,1.000000,1.0
1331,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,4,5.5264,...,0.983051,15.47,0.737018,0.777217,12.0,1.000000,19.06,0.908051,0.957582,4.0
1332,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,5,4.5313,...,0.966667,10.24,0.800000,0.828555,7.0,1.000000,12.80,1.000000,1.000000,1.0
1333,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,6,5.1048,...,0.965517,7.77,0.708295,0.735636,7.0,0.965517,9.38,0.855059,0.855061,2.0
1334,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,7,4.6656,...,1.000000,11.27,0.832815,0.906575,5.0,1.000000,12.03,0.935459,0.935459,2.0
1335,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,8,6.6667,...,1.000000,19.35,0.748333,0.848688,8.0,1.000000,23.41,0.975417,0.987762,2.0