In [1]:
from lib.data import get_data
from lib.stats import stage_standing, match_standing

df = get_data("fitds_stages")

stage_df = stage_standing(df, 'monster_2025', 'P', 1)
match_df = match_standing(df, 'monster_2025', 'P')

2026-03-14 07:14:06.262 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-14 07:14:06.263 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-14 07:14:06.264 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-14 07:14:06.265 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-14 07:14:06.265 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-03-14 07:14:06.268 No runtime found, using MemoryCacheStorageManager

In [2]:
match_df

,shooter_div,rank,shooter_name,shooter_class,stg_match_pts,pct
0,P,1,"PERAZZOLI, FRANCESCO",G,1792.046,1.0000
1,P,2,"SÁNCHEZ, CARLOS",NaN,1769.958,0.9877
2,P,3,"BERGAMO, BRICE",NaN,1729.782,0.9653
3,P,4,"BUTICCHI, EDOARDO ROBERTO",G,1700.134,0.9487
4,P,5,"PIGNATTI, ALBERTO",M,1672.716,0.9334
...,...,...,...,...,...,...
70,P,71,"VITALI, FEDERICA",D,707.370,0.3947
71,P,72,"AMBROSIO, CRISTIAN",D,706.210,0.3941
72,P,73,"BONFANTI, FRANCESCO",D,602.480,0.3362
73,P,74,"SALEMI, ALBERTO",C,532.536,0.2972
74,P,75,"FANTINATI, ALESSANDRO",D,0.000,0.0000

In [4]:
df[(df['shooter_name'] == 'ABATECOLA, CHRISTIAN') & (df['match_name'] == 'ma5_2_2025')]

,match_name,match_level,match_date,shooter_name,shooter_div,shooter_class,shooter_pf,shooter_cat,stg_n,hf,...,div_pts_perc_abcd,div_first_time_abcd,div_time_perc_abcd,div_factor_perc_abcd,div_factor_standing_abcd,cls_pts_perc_abcd,cls_first_time_abcd,cls_time_perc_abcd,cls_factor_perc_abcd,cls_factor_standing_abcd
1328,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,1,4.6523,...,0.833333,15.19,0.743879,0.673719,11.0,0.833333,17.88,0.875612,0.815521,3.0
1329,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,2,3.5685,...,0.716667,10.99,0.912033,0.700324,3.0,0.741379,12.05,1.000000,1.000000,1.0
1330,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,3,6.8875,...,1.000000,17.87,0.778989,0.854719,4.0,1.000000,21.41,0.933304,1.000000,1.0
1331,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,4,5.5264,...,0.983051,15.47,0.737018,0.777217,12.0,1.000000,19.06,0.908051,0.957582,4.0
1332,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,5,4.5313,...,0.966667,10.24,0.800000,0.828555,7.0,1.000000,12.80,1.000000,1.000000,1.0
1333,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,6,5.1048,...,0.965517,7.77,0.708295,0.735636,7.0,0.965517,9.38,0.855059,0.855061,2.0
1334,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,7,4.6656,...,1.000000,11.27,0.832815,0.906575,5.0,1.000000,12.03,0.935459,0.935459,2.0
1335,ma5_2_2025,2,2025-02-23,"ABATECOLA, CHRISTIAN",PO,B,Minor,NaN,8,6.6667,...,1.000000,19.35,0.748333,0.848688,8.0,1.000000,23.41,0.975417,0.987762,2.0