In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\antob\Documents\MEGA\Documenti\Armi\Gare\app\ipsc-performance\data\IPSC.csv')
df

,match_name,match_level,match_date,shooter,div,class,power_factor,cat,stg,factor,pts,a,c,d,ded,mi,ns,pe,ot,time
0,2025_MA5_2,2,2025-02-23,"DEL CANUTO, ANDREA",S,C,Minor,S,Stage 1,0.4822,10,11,4,3,0,6,0,0,NaN,20.74
1,2025_MA5_2,2,2025-02-23,"LAURO, ANDREA",P,D,Minor,NaN,Stage 2,0.3584,9,6,3,0,0,3,0,0,NaN,25.11
2,2025_MA5_2,2,2025-02-23,"LAURO, ANDREA",P,D,Minor,NaN,Stage 1,1.8833,61,15,5,1,0,3,0,0,NaN,32.39
3,2025_MA5_2,2,2025-02-23,"SOLIDANI, TOMMASO",C,A,Minor,NaN,Stage 8,5.5656,154,29,3,0,0,0,0,0,NaN,27.67
4,2025_MA5_2,2,2025-02-23,"SOLIDANI, TOMMASO",C,A,Minor,NaN,Stage 7,2.2333,54,10,1,1,0,0,0,0,NaN,24.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26573,2025_W4_5,2,2025-11-30,"TAGLIATI, ROBERTO",SO,B,Minor,S,Stage 2,5.0290,52,9,2,1,0,0,0,0,NaN,10.34
26574,2025_W4_5,2,2025-11-30,"TAGLIATI, ROBERTO",SO,B,Minor,S,Stage 3,5.2905,102,17,5,2,0,0,0,0,NaN,19.28
26575,2025_W4_5,2,2025-11-30,"TAGLIATI, ROBERTO",SO,B,Minor,S,Stage 4,2.1563,16,8,2,0,0,2,1,0,NaN,7.42
26576,2025_W4_5,2,2025-11-30,"FEDELI, ALESSANDRO",C,A,Minor,S,Stage 4,5.8893,50,8,3,1,0,0,0,0,NaN,8.49
26577,2025_W4_5,2,2025-11-30,"BALESTRINI, BARBARA",PO,A,Minor,LS,Stage 6,8.1433,150,27,5,0,0,0,0,0,NaN,18.42

In [4]:
df[df['shooter'] == 'BUZZELLI, ANTONIO'].groupby('match_name').agg({'stg': 'size'})

              stg
match_name
2025_BERETTA   14
2025_ITA_4     10
2025_MA5_2      8
2025_MA5_3      8
2025_MA5_4      8
2025_MA5_5      8
2025_MONSTER   20
2025_W4_2       6
2025_W4_5       6
2025_W5_1       6
2025_W5_2       6
2025_W5_3       6
2025_W5_4       6